apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{.Values.ingressClassName}}
  rules:
    - host: {{.Values.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mock-app-service
                port:
                  number: 5000
